const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('anton', {
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  refreshWorkspace: () => ipcRenderer.invoke('workspace:refresh'),
  openFileDialog: () => ipcRenderer.invoke('dialog:openFile'),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  fileStats: (filePath) => ipcRenderer.invoke('file:stats', filePath),
  readFileRange: (payload) => ipcRenderer.invoke('file:readRange', payload),
  searchFile: (payload) => ipcRenderer.invoke('file:search', payload),
  outlineFile: (filePath) => ipcRenderer.invoke('file:outline', filePath),
  replaceRange: (payload) => ipcRenderer.invoke('file:replaceRange', payload),
  insertAtLine: (payload) => ipcRenderer.invoke('file:insertAtLine', payload),
  deleteRange: (payload) => ipcRenderer.invoke('file:deleteRange', payload),
  saveFile: (payload) => ipcRenderer.invoke('file:save', payload),
  createFile: (payload) => ipcRenderer.invoke('file:create', payload),
  deleteFile: (filePath) => ipcRenderer.invoke('file:delete', filePath),
  renameFile: (payload) => ipcRenderer.invoke('file:rename', payload),
  duplicateFile: (filePath) => ipcRenderer.invoke('file:duplicate', filePath),
  revealFile: (filePath) => ipcRenderer.invoke('file:reveal', filePath),
  writeClipboard: (text) => ipcRenderer.invoke('clipboard:write', text),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  searchWorkspace: (query) => ipcRenderer.invoke('workspace:search', query),
  rebuildIndex: () => ipcRenderer.invoke('index:rebuild'),
  searchIndex: (payload) => ipcRenderer.invoke('index:search', payload),
  indexStatus: () => ipcRenderer.invoke('index:status'),
  createSnapshot: (payload) => ipcRenderer.invoke('snapshot:create', payload),
  listSnapshots: () => ipcRenderer.invoke('snapshot:list'),
  restoreSnapshot: (payload) => ipcRenderer.invoke('snapshot:restore', payload),
  classifyCommand: (payload) => ipcRenderer.invoke('command:classify', payload),
  createPendingEdit: (payload) => ipcRenderer.invoke('agent:createPendingEdit', payload),
  applyPendingEdit: (payload) => ipcRenderer.invoke('agent:applyPendingEdit', payload),
  rejectPendingEdit: (payload) => ipcRenderer.invoke('agent:rejectPendingEdit', payload),
  detectVerification: () => ipcRenderer.invoke('verify:detect'),
  runVerification: () => ipcRenderer.invoke('verify:run'),
  verifyBrowser: (payload) => ipcRenderer.invoke('browser:verify', payload),
  gitStatus: (payload) => ipcRenderer.invoke('git:status', payload),
  gitDiff: (payload) => ipcRenderer.invoke('git:diff', payload),
  gitStage: (payload) => ipcRenderer.invoke('git:stage', typeof payload === 'string' ? { path: payload } : payload),
  gitUnstage: (payload) => ipcRenderer.invoke('git:unstage', typeof payload === 'string' ? { path: payload } : payload),
  gitStageAll: (payload) => ipcRenderer.invoke('git:stageAll', payload),
  gitUnstageAll: (payload) => ipcRenderer.invoke('git:unstageAll', payload),
  gitDiscard: (payload) => ipcRenderer.invoke('git:discard', payload),
  gitDiscardAll: (payload) => ipcRenderer.invoke('git:discardAll', payload),
  gitCommit: (payload) => ipcRenderer.invoke('git:commit', typeof payload === 'string' ? { message: payload } : payload),
  gitPull: (payload) => ipcRenderer.invoke('git:pull', payload),
  gitPush: (payload) => ipcRenderer.invoke('git:push', payload),
  gitSync: (payload) => ipcRenderer.invoke('git:sync', payload),
  gitBranches: (payload) => ipcRenderer.invoke('git:branches', payload),
  gitCreateBranch: (payload) => ipcRenderer.invoke('git:createBranch', typeof payload === 'string' ? { branchName: payload } : payload),
  gitCheckoutBranch: (payload) => ipcRenderer.invoke('git:checkoutBranch', typeof payload === 'string' ? { branchName: payload } : payload),
  gitStash: (payload) => ipcRenderer.invoke('git:stash', typeof payload === 'string' ? { message: payload } : payload),
  gitStashPop: (payload) => ipcRenderer.invoke('git:stashPop', typeof payload === 'string' ? { stashRef: payload } : payload),
  gitStashList: (payload) => ipcRenderer.invoke('git:stashList', payload),
  loadChat: (workspacePath) => ipcRenderer.invoke('chat:load', workspacePath),
  saveChat: (payload) => ipcRenderer.invoke('chat:save', payload),
  listChats: () => ipcRenderer.invoke('chat:list'),
  loadChatById: (id) => ipcRenderer.invoke('chat:loadById', id),
  abortGenerate: (requestId) => ipcRenderer.invoke('ollama:abort', requestId),
  createTerminal: (payload) => ipcRenderer.invoke('terminal:create', payload),
  useWorkspaceRootTerminal: (payload) => ipcRenderer.invoke('terminal:useWorkspaceRoot', payload),
  runTerminal: (payload) => ipcRenderer.invoke('terminal:run', payload),
  killTerminal: (payload) => ipcRenderer.invoke('terminal:kill', payload),
  executeCommand: (payload) => ipcRenderer.invoke('terminal:executeCommand', payload),
  toggleKeepAwake: (enabled) => ipcRenderer.invoke('power:toggleKeepAwake', enabled),
  listModels: () => ipcRenderer.invoke('ollama:listModels'),
  catalogModels: () => ipcRenderer.invoke('ollama:catalogModels'),
  pullModel: (payload) => ipcRenderer.invoke('ollama:pullModel', payload),
  deleteModel: (payload) => ipcRenderer.invoke('ollama:deleteModel', payload),
  generate: (payload) => ipcRenderer.invoke('ollama:generate', payload),
  sendOpenClawMessage: (payload) => ipcRenderer.invoke('openclaw:send', payload),
  getOpenClawModelInfo: () => ipcRenderer.invoke('openclaw:getModelInfo'),
  setOpenClawModel: (model) => ipcRenderer.invoke('openclaw:setModel', model),
  onWorkspaceChanged: (callback) => ipcRenderer.on('workspace:changed', (_event, payload) => callback(payload)),
  onTerminalData: (callback) => ipcRenderer.on('terminal:data', (_event, payload) => callback(payload)),
  onTerminalClear: (callback) => ipcRenderer.on('terminal:clear', (_event, payload) => callback(payload)),
  onTerminalCwd: (callback) => ipcRenderer.on('terminal:cwd', (_event, payload) => callback(payload)),
  onTerminalState: (callback) => ipcRenderer.on('terminal:state', (_event, payload) => callback(payload)),
  onOllamaToken: (callback) => ipcRenderer.on('ollama:token', (_event, payload) => callback(payload)),
  onOllamaPullProgress: (callback) => ipcRenderer.on('ollama:pullProgress', (_event, payload) => callback(payload))
});
